#!/usr/bin/env bash

# run as: $ sudo sh script/install


set -x


#
# Install icons
#

DIR_ICO="/usr/share/icons/hicolor"


install -D -m 644                   \
    "icons/graphinator_plugin.svg"  \
    "$DIR_ICO/scalable/apps/graphinator-plugin.svg"


install -D -m 644                   \
    icons/graphinator_plugin_24.png \
    "$DIR_ICO/24x24/apps/graphinator-plugin.png"


install -D -m 644                   \
    icons/graphinator_plugin_48.png \
    "$DIR_ICO/48x48/apps/graphinator-plugin.png"


install -D -m 644                   \
    icons/graphinator_plugin_64.png \
    "$DIR_ICO/64x64/apps/graphinator-plugin.png"


gtk-update-icon-cache $DIR_ICO


#
# Install shared library and .desktop file
#

NAME="graphinator"
LIB="panel-plugin/.libs/lib$NAME.so"

DIR_LIB="/usr/lib/x86_64-linux-gnu"
DIR_DESKTOP="/usr/share/xfce4/panel/plugins"


install -m 744                      \
    "$LIB"                          \
    "$DIR_LIB/xfce4/panel/plugins/lib$NAME.so"

install -m 644                      \
    "panel-plugin/$NAME.desktop"    \
    "$DIR_DESKTOP/$NAME.desktop"

