#!/usr/bin/env bash

# run as: $ sudo sh script/uninstall


set -x


#
# UNINSTALL icons
#

DIR_ICO="/usr/share/icons/hicolor"

rm \
    $DIR_ICO/scalable/apps/graphinator-plugin.svg   \
    $DIR_ICO/24x24/apps/graphinator-plugin.png      \
    $DIR_ICO/48x48/apps/graphinator-plugin.png      \
    $DIR_ICO/64x64/apps/graphinator-plugin.png



#
# UNINSTALL shared library and .desktop file
#

NAME="graphinator"
LIB="panel-plugin/.libs/lib$NAME.so"

DIR_LIB="/usr/lib/x86_64-linux-gnu"
DIR_DESKTOP="/usr/share/xfce4/panel/plugins"

rm  \
    "$DIR_LIB/xfce4/panel/plugins/lib$NAME.so"      \
    "$DIR_DESKTOP/$NAME.desktop"
